import

In [242]:
import pandas as pd 
import numpy as np 
from scipy import stats as st
import statistics as s 

import seaborn as sns
sns.set_style("darkgrid")

# Rozpocznijmy od zadań związanych z manipulacją tablicami.

## Zadanie 1

Rozpocznijmy od zadań związanych z manipulacją tablicami.

Postaraj się rozwiązać podane poniżej zadania więcej niż jednym sposobem.

* Stwórz np.ndarray zawierający liczby od 0 do 100.
* Stwórz np.ndarray zawierający liczby od 0 do 1000, które są podzielne przez liczbę 11. Zadbaj o to, aby liczby ułożone były w kolejności malejącej.
*Stwórz np.ndarray zawierający 70 jednakokowo od siebie odległych liczb z przedziału -5 do 5


In [14]:
# Stwórz np.ndarray zawierający liczby od 0 do 100.
x = [i for i in range(101)]
x = np.array(x)

x_2 = np.arange(0, 101, 1)
x, x_2

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100]),
 array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  

In [27]:
# Stwórz np.ndarray zawierający liczby od 0 do 1000, które są podzielne przez liczbę 11. 
# Zadbaj o to, aby liczby ułożone były w kolejności malejącej.

x = np.arange(0,1001,1)[::-1]
x = [i for i in x if i % 11 == 0]

x_2 = np.array([i for i in range(1001) if i % 11 == 0])[::-1]

x, x_2

([990,
  979,
  968,
  957,
  946,
  935,
  924,
  913,
  902,
  891,
  880,
  869,
  858,
  847,
  836,
  825,
  814,
  803,
  792,
  781,
  770,
  759,
  748,
  737,
  726,
  715,
  704,
  693,
  682,
  671,
  660,
  649,
  638,
  627,
  616,
  605,
  594,
  583,
  572,
  561,
  550,
  539,
  528,
  517,
  506,
  495,
  484,
  473,
  462,
  451,
  440,
  429,
  418,
  407,
  396,
  385,
  374,
  363,
  352,
  341,
  330,
  319,
  308,
  297,
  286,
  275,
  264,
  253,
  242,
  231,
  220,
  209,
  198,
  187,
  176,
  165,
  154,
  143,
  132,
  121,
  110,
  99,
  88,
  77,
  66,
  55,
  44,
  33,
  22,
  11,
  0],
 array([990, 979, 968, 957, 946, 935, 924, 913, 902, 891, 880, 869, 858,
        847, 836, 825, 814, 803, 792, 781, 770, 759, 748, 737, 726, 715,
        704, 693, 682, 671, 660, 649, 638, 627, 616, 605, 594, 583, 572,
        561, 550, 539, 528, 517, 506, 495, 484, 473, 462, 451, 440, 429,
        418, 407, 396, 385, 374, 363, 352, 341, 330, 319, 308, 297, 286,
        

In [33]:
# Stwórz np.ndarray zawierający 70 jednakokowo od siebie odległych liczb z przedziału -5 do 5

np.linspace(-5,5,70)

array([-5.        , -4.85507246, -4.71014493, -4.56521739, -4.42028986,
       -4.27536232, -4.13043478, -3.98550725, -3.84057971, -3.69565217,
       -3.55072464, -3.4057971 , -3.26086957, -3.11594203, -2.97101449,
       -2.82608696, -2.68115942, -2.53623188, -2.39130435, -2.24637681,
       -2.10144928, -1.95652174, -1.8115942 , -1.66666667, -1.52173913,
       -1.37681159, -1.23188406, -1.08695652, -0.94202899, -0.79710145,
       -0.65217391, -0.50724638, -0.36231884, -0.2173913 , -0.07246377,
        0.07246377,  0.2173913 ,  0.36231884,  0.50724638,  0.65217391,
        0.79710145,  0.94202899,  1.08695652,  1.23188406,  1.37681159,
        1.52173913,  1.66666667,  1.8115942 ,  1.95652174,  2.10144928,
        2.24637681,  2.39130435,  2.53623188,  2.68115942,  2.82608696,
        2.97101449,  3.11594203,  3.26086957,  3.4057971 ,  3.55072464,
        3.69565217,  3.84057971,  3.98550725,  4.13043478,  4.27536232,
        4.42028986,  4.56521739,  4.71014493,  4.85507246,  5.  

## Zadanie 2
Stwórz macierze, takie jak przedstawiono poniżej, a następnie z ich pomocą przeprowadź kilka operacji matematycznych.

[[1 4 7]

 [2 5 8]
 
 [3 6 9]]




[[3 2 3]

 [4 3 1]
 
 [7 3 1]]

Oblicz:
* sumę
* różnice
* Transpozycję obu macierzy
* Mnożenie macierzy element-wise
* Dzielenie macierzy element-wise
* Iloczyn macierzy


In [53]:
matrix = np.array([[1, 4, 7],
                   [2, 5, 8],
                   [3, 6, 9]])

matrix_2 =  np.array([[3, 2, 3],
                      [4, 3, 1],
                      [7, 3, 1]])
                  
add = np.add(matrix, matrix_2), matrix + matrix_2
sub = np.subtract(matrix, matrix_2), matrix - matrix_2
tr = np.transpose(matrix), matrix.T # np.transpose(matrix_2),  matrix_2.T
m = np.multiply(matrix, matrix_2), matrix * matrix_2
d = np.divide(matrix, matrix_2), matrix / matrix_2
m_prod = np.matmul(matrix, matrix_2), matrix @ matrix_2

## Zadanie 

Oblicz:

* Stwórz np.array zawierający cosinusy i sinusy wartości bedących w przedziale od 0 do pi, kolejne liczby powinny być od siebie większe o 1/10 radiana.

* Stwórz np.array zawierający liczby od -100 do 100, gdzie każda następna liczba jest większa od poprzedniej o 2 (-100, -98, -96… 98, 100).

* Oblicz 20 pierwszych kwadratów.

* Oblicz sumę tablic, tak aby element na pozycji 'i' był sumą i-tego elementu z pierwszej tablicy oraz elementu len(array)-1-i drugiej tablicy. Użyj tablicy pierwszych 20 kwadratów oraz 20 sześcianów.

In [58]:
# Stwórz np.array zawierający cosinusy i sinusy wartości bedących w przedziale 
# od 0 do pi, kolejne liczby powinny być od siebie większe o 1/10 radiana.

numbers = np.arange(0, 3.14, 0.1)
s, c =np.sin(numbers), np.cos(numbers) 
s, c

(array([0.        , 0.09983342, 0.19866933, 0.29552021, 0.38941834,
        0.47942554, 0.56464247, 0.64421769, 0.71735609, 0.78332691,
        0.84147098, 0.89120736, 0.93203909, 0.96355819, 0.98544973,
        0.99749499, 0.9995736 , 0.99166481, 0.97384763, 0.94630009,
        0.90929743, 0.86320937, 0.8084964 , 0.74570521, 0.67546318,
        0.59847214, 0.51550137, 0.42737988, 0.33498815, 0.23924933,
        0.14112001, 0.04158066]),
 array([ 1.        ,  0.99500417,  0.98006658,  0.95533649,  0.92106099,
         0.87758256,  0.82533561,  0.76484219,  0.69670671,  0.62160997,
         0.54030231,  0.45359612,  0.36235775,  0.26749883,  0.16996714,
         0.0707372 , -0.02919952, -0.12884449, -0.22720209, -0.32328957,
        -0.41614684, -0.5048461 , -0.58850112, -0.66627602, -0.73739372,
        -0.80114362, -0.85688875, -0.90407214, -0.94222234, -0.97095817,
        -0.9899925 , -0.99913515]))

In [60]:
# Stwórz np.array zawierający liczby od -100 do 100, gdzie każda następna 
# liczba jest większa od poprzedniej o 2 (-100, -98, -96… 98, 100).
np.arange(-100, 101, 2)

array([-100,  -98,  -96,  -94,  -92,  -90,  -88,  -86,  -84,  -82,  -80,
        -78,  -76,  -74,  -72,  -70,  -68,  -66,  -64,  -62,  -60,  -58,
        -56,  -54,  -52,  -50,  -48,  -46,  -44,  -42,  -40,  -38,  -36,
        -34,  -32,  -30,  -28,  -26,  -24,  -22,  -20,  -18,  -16,  -14,
        -12,  -10,   -8,   -6,   -4,   -2,    0,    2,    4,    6,    8,
         10,   12,   14,   16,   18,   20,   22,   24,   26,   28,   30,
         32,   34,   36,   38,   40,   42,   44,   46,   48,   50,   52,
         54,   56,   58,   60,   62,   64,   66,   68,   70,   72,   74,
         76,   78,   80,   82,   84,   86,   88,   90,   92,   94,   96,
         98,  100])

In [75]:
# Oblicz 20 pierwszych kwadratów.
x = [2 ** i for i in range(21)]
x = np.array(x)

x_2 = np.array([2 ** i for i in range(21)])

In [80]:
# Oblicz sumę tablic, tak aby element na pozycji 'i' był sumą i-tego elementu 
# z pierwszej tablicy oraz elementu len(array)-1-i drugiej tablicy.  
# Użyj tablicy pierwszych 20 kwadratów oraz 20 sześcianów.

x = np.arange(0,21) ** 2
y = np.arange(0,21) ** 3
res = x + y[::-1]

x = np.arange(0,21) ** 2
y = np.arange(0,21)[::-1] ** 3
res_2 = x + y

n = np.arange(0,21) 
res_3 = n**2 + n[::-1]**3

res, res_2, res_3

(array([8000, 6860, 5836, 4922, 4112, 3400, 2780, 2246, 1792, 1412, 1100,
         850,  656,  512,  412,  350,  320,  316,  332,  362,  400]),
 array([8000, 6860, 5836, 4922, 4112, 3400, 2780, 2246, 1792, 1412, 1100,
         850,  656,  512,  412,  350,  320,  316,  332,  362,  400]),
 array([8000, 6860, 5836, 4922, 4112, 3400, 2780, 2246, 1792, 1412, 1100,
         850,  656,  512,  412,  350,  320,  316,  332,  362,  400]))

## Zadanie 
Stwórz tablicę 100 elementową od 1 do 101 dla każdego wzoru ciągu podanego poniżej.

Oblicz sumę wszystkich elementów.


* 1/n (rezultat = 5.1972785077386305)
* 1/sqt(n) (rezultat = 18.689107543805147)
* (1+1/n)^n (rezultat = 268.74089438451426)

In [95]:
n = np.arange(1,102)

In [96]:
sum(1/n)

5.1972785077386305

In [97]:
sum(1/np.sqrt(n))

18.689107543805147

In [98]:
sum((1+1/n)**n)

268.74089438451426

## Zadanie 

Stwórz macierz A o wymiarach 7x7. Wypełnij ją dowolnymi wartościami - np. liczbami od 0 do 48.

* Znajdź element z 3 rzędu i 4 kolumny
* Zastąp liczbę występującą w 6 rzędzie i 3 kolumnie liczbą pi.
* Stwórz macierz B zawierającą pierwsze 3 rzędy oraz wszystkie kolumny poza ostatnią macierzy A.
* Stwórz macierz zawierającą elementy z 2 pierwszych kolumn
* Stwórz macierz zawierającą 4 ostatnie rzędy

In [103]:
matrix = np.arange(0,49).reshape(7,7)

In [106]:
matrix[2,3]

17

In [117]:
# Zastąp liczbę występującą w 6 rzędzie i 3 kolumnie liczbą pi.
matrix[6][2] = np.pi
matrix

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43,  3, 45, 46, 47, 48]])

In [122]:
# Stwórz macierz B zawierającą pierwsze 3 rzędy oraz wszystkie kolumny poza ostatnią macierzy A.
matrix_b = matrix[:3,:-1]
matrix_b

array([[ 0,  1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11, 12],
       [14, 15, 16, 17, 18, 19]])

In [124]:
# Stwórz macierz zawierającą elementy z 2 pierwszych kolumn
matrix_c = matrix[:,:2]
matrix_c

array([[ 0,  1],
       [ 7,  8],
       [14, 15],
       [21, 22],
       [28, 29],
       [35, 36],
       [42, 43]])

In [129]:
# Stwórz macierz zawierającą 4 ostatnie rzędy
matrix_d = matrix[-4:,:]
matrix_d

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43,  3, 45, 46, 47, 48]])

## Zadanie 
Stwórz wektor posiadający 36 elementów, a następnie przekształć go do macierzy o podanym rozmiarze

* 2x18
* 3x12
* 4x9

In [132]:
matrix = np.arange(0,36)

In [133]:
matrix.reshape(2,18)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35]])

In [134]:
matrix.reshape(3,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [135]:
matrix.reshape(4,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

## Zadanie 
Stwórz macierz 100x100 o następującej strukturze i wartościach.

[[  1.   1.   1. ...   1.   1.   1.]

 [  2.   2.   2. ...   2.   2.   2.]
 
 [  3.   3.   3. ...   3.   3.   3.]
 ...
 
 [ 98.  98.  98. ...  98.  98.  98.]
 
 [ 99.  99.  99. ...  99.  99.  99.]
 
 [100. 100. 100. ... 100. 100. 100.]]

In [159]:
x = [[i] * 100 for i in range(1,101)]
res = np.array(x).reshape(100,100)

res_2 = np.array( [np.arange(1,101)] * 100).T

res, res_2

(array([[  1,   1,   1, ...,   1,   1,   1],
        [  2,   2,   2, ...,   2,   2,   2],
        [  3,   3,   3, ...,   3,   3,   3],
        ...,
        [ 98,  98,  98, ...,  98,  98,  98],
        [ 99,  99,  99, ...,  99,  99,  99],
        [100, 100, 100, ..., 100, 100, 100]]),
 array([[  1,   1,   1, ...,   1,   1,   1],
        [  2,   2,   2, ...,   2,   2,   2],
        [  3,   3,   3, ...,   3,   3,   3],
        ...,
        [ 98,  98,  98, ...,  98,  98,  98],
        [ 99,  99,  99, ...,  99,  99,  99],
        [100, 100, 100, ..., 100, 100, 100]]))

## Zadanie 
Stwórz trzy macierze 2x5 wraz z elementami [0,..9], [10,..19], [20,..29]. Stwórz z nich macierze 3D łącząc je wzdłuż osi 0, 1 i 2

* Wyświetl wartości znajdujące się pod indeksami [0,0,0] oraz [0,1,1].
* Wyświetl kształt tych macierzy
* Oblicz sume tych macierzy

In [173]:
a = np.arange(0,10).reshape(2,5)
b = np.arange(10,20).reshape(2,5)
c = np.arange(20,30).reshape(2,5)

d = np.stack((a, b, c), axis=0)
d_1 = np.stack((a, b, c), axis=1)
d_2 = np.stack((a, b, c), axis=2)

In [177]:
# Wyświetl wartości znajdujące się pod indeksami [0,0,0] oraz [0,1,1].
print(d[0,0,0],"\n", d_1[0,0,0],"\n", d_2[0,0,0],"\n", d[0,1,1],"\n",\
      d_1[0,1,1],"\n", d_2[0,1,1])

0 
 0 
 0 
 6 
 11 
 11


In [178]:
# Wyświetl kształt tych macierzy
print(d.shape,"\n",d_1.shape,"\n",d_2.shape,"\n")

(3, 2, 5) 
 (2, 3, 5) 
 (2, 5, 3) 



In [179]:
# Oblicz sume tych macierzy
np.sum(d), np.sum(d), np.sum(d)

(435, 435, 435)

# Statystyka opisowa

## Zadanie 1
Pobierz MDR_RR_TB_burden_estimates_2022-01-12.csv.

Załóż, że iso_numeric jest wartością numeryczną. 

* Spróbuj załadować ją za pomocą np.loadtxt a następnie przekształcić ją na zmieną typu float. Wyrzuć wartości nieznane.
* Stwórz funkcję, która oblicza podstawowe statystyki, takie jak: max, min, średnia, mediana, odchylenie standardowe, wariancja.

In [217]:
def converter(x):
    try:
        return float(x.decode("utf-8").replace('"', ''))
    except ValueError:
        print('non-numerical input')

data = np.loadtxt(
        r"C:\Users\user\Desktop\Data Science\SDA\SDA szkolenie\Statystyka i prawdopodoby\csv\MDR_RR_TB_burden_estimates_2022-01-12.csv",     
        delimiter=',', 
        usecols=(3), 
        converters = {3: converter},
        skiprows=1, 
        unpack=True
    )
    
data = data[np.logical_not(np.isnan(data))]
data

non-numerical input
non-numerical input
non-numerical input


array([  4.,   8.,  12.,  16.,  20.,  24., 660.,  28.,  32.,  51., 533.,
        36.,  40.,  31.,  44.,  48.,  50.,  52., 112.,  56.,  84., 204.,
        60.,  64.,  68.,  70.,  72.,  76.,  92.,  96., 100., 854., 108.,
       132., 116., 120., 124., 136., 140., 148., 152., 156., 170., 174.,
       178., 184., 188., 384., 191., 192., 531., 196., 203., 408., 180.,
       208., 262., 212., 214., 218., 818., 222., 226., 232., 233., 748.,
       231., 242., 246., 250., 258., 266., 270., 268., 276., 288., 300.,
       304., 308., 316., 320., 324., 624., 328., 332., 340., 348., 352.,
       356., 360., 364., 368., 372., 376., 380., 388., 392., 400., 398.,
       404., 296., 414., 417., 418., 428., 422., 426., 430., 434., 440.,
       442., 450., 454., 458., 462., 466., 470., 584., 478., 480., 484.,
       583., 492., 496., 499., 500., 504., 508., 104., 516., 520., 524.,
       528., 540., 554., 558., 562., 566., 570., 807., 580., 578., 512.,
       586., 585., 591., 598., 600., 604., 608., 61

In [ ]:
# Stwórz funkcję, która oblicza podstawowe statystyki, takie jak: 
# max, min, średnia, mediana, odchylenie standardowe, wariancja.

In [225]:
def statistiks(df):
    print("max: ",df.max())
    print("min: ",df.min())
    print("mean: ",df.mean())
    print("median: ",np.median(df))
    print("std: ",df.std())
    print("wariancja: ",df.var())
    
statistiks(data)

max:  894.0
min:  4.0
mean:  434.3066037735849
median:  437.0
std:  254.1044306077786
wariancja:  64569.06165450337


## Zadanie 
Pobierz Wzrost.csv.

Oblicz podstawowe statystki tak jak powyżej. Zastanów się, jaka jest różnica pomiędzy wartością wariancji, a odchylenia standardowego. Dlaczego taka różnica występuje? Postaraj się rozszerzyć zawartość Twojej funkcji, wyświetlającej podstawowe statystyki o nowe metody z biblioteki statistics oraz scipy.stats.modules

In [234]:
data = np.loadtxt(r"C:\Users\user\Desktop\Data Science\SDA\SDA szkolenie\Statystyka i prawdopodoby\csv\Wzrost.csv",  
                 delimiter=',', encoding= "utf-8" )
data

array([156., 158., 167., 188., 197., 167., 197., 178., 186., 157., 198.,
       199., 178., 168., 156., 151., 167., 167.])

In [264]:
print( "median_high: ", s.median_high(data),"\n",  \
       "median_high: ", s.median_high(data),"\n", \
        "median_low: ", s.median_low(data),"\n",  \
        "mode: ",       s.mode(data),"\n",        \
        "pvariance: ",  s.pvariance(data),"\n",   \
        "variance: ",   s.variance(data),"\n",    \
        "pstdev: ",     s.pstdev(data),"\n",      \
        "stdev: ",      s.stdev(data)        )
print()
print( "kurtosis:", st.kurtosis(data) )
print( "skewness:", st.skew(data) )
st.describe(data)

median_high:  168.0 
 median_high:  168.0 
 median_low:  167.0 
 mode:  167.0 
 pvariance:  254.69444444444446 
 variance:  269.6764705882353 
 pstdev:  15.95914923936876 
 stdev:  16.42182908777933

kurtosis: -1.3074579340561316
skewness: 0.29608077170359876


DescribeResult(nobs=18, minmax=(151.0, 199.0), mean=174.16666666666666, variance=269.67647058823536, skewness=0.29608077170359876, kurtosis=-1.3074579340561316)

## Zadanie 3

Znajdź dowolny inny zbiór danych csv w Internecie. Spróbuj przeanalizować wartości numeryczne występujące w pliku z pomocą Twojej funkcji.

# Rozkłady prawdopodobieństwa zmiennych losowych

## Zadanie 

Wygeneruj 1000 liczb z rozkładu Bernoulliego.

W tym celu wykorzystaj: scipy. Spróbuj dowiedzieć się, jak hiperparametr - prawdopodobieństwo sukcesu p, wpływa na średnią, wariancję, skośność, kurtozę wygenerowanego zbioru.

In [296]:
def prin_stats(data):
    print("mean:",np.mean(data))
    print("var:",np.var(data))    
    print("skew:",st.skew(data))
    print("kurtosis:",st.kurtosis(data))    
    print()

In [297]:
p = .3  # gdzie p jest prawdopodobieństwem pojedynczego sukcesu, 
        # a 1 - p jest prawdopodobieństwem pojedynczej porażki.
    
data = st.bernoulli.rvs(p, size = 1000)
mean, var, skew, kurt = st.bernoulli.stats(p, moments ='mvsk')

prin_stats(data)
print("mean:", mean,"\nvar:", var,"\nskew:", skew,"\nkurt:", kurt )

mean: 0.271
var: 0.19755899999999996
skew: 1.0304266169174092
kurtosis: -0.9382209871481422

mean: 0.3 
var: 0.21 
skew: 0.8728715609439694 
kurt: -1.2380952380952381


## Zadanie 

Wygeneruj 100 próbek z następujących rozkładów: Bernoulli, Binomial, Poisson.

Oblicz ich podstawowe statystyki (średnią, wariancję, kurtozę oraz skośność).

Postaraj się pomyśleć o róznicach pomiędzy poszczególnymi rozkładami bazując na obliczonych statystykach.

In [305]:
#Bernoulli
p = 0.3 
mean, var, skew, kurt = st.bernoulli.stats(p, moments ='mvsk')
print(mean, var, skew, kurt)

#Binomial
n, p = 5, 0.4
mean, var, skew, kurt = st.binom.stats(n, p, moments='mvsk')
print(mean, var, skew, kurt)

#Poisson
mu = 0.6
mean, var, skew, kurt = st.poisson.stats(mu, moments='mvsk')
print(mean, var, skew, kurt)

0.3 0.21 0.8728715609439694 -1.2380952380952381
2.0 1.2 0.18257418583505533 -0.3666666666666668
0.6 0.6 1.2909944487358056 1.6666666666666667


# Testy statystyczne

## Zadanie 1
Wygeneruj 200 próbek z rozkładu normalnego o średniej 2 oraz odchyleniu standardowym 30. 

Przetestuj hipotezę, że średnia tej dystrybucji jest równa 2.5.

Info:

Przyjmij poziom ufności α = 0.05

Extra:

Postaraj się powtórzyć ten test kilka razy. Zlicz ile razy hipoteza została zaakceptowana. Następnie zrób to samo z użyciem mniejszej próby.

In [365]:
def test(a = 0.05, n = 200, m = 2, std = .3 ):
    era = 1000 
    success = {}
    
    for i in range(era):
        data = st.norm.rvs(loc= m, scale= std, size= n)
        res = st.ttest_1samp(data, 2.5 )
        if res.pvalue > a: success[i] = res.pvalue
            
    return success if success else "Hipothesis rejected!"

print(test())

for i in range(200,0,-10):
    print(test(n = i))

Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
Hipothesis rejected!
{989: 0.07772600863283238}


## Zadanie 2
Pobierz napoje.csv. 

Sprawdź hipotezę:

* średnia konsumpcja piwa lech = 60.500 
* średnia konsumpcja coli = 222.000 
* średnia konsumpcja regionalnego piwa = 43.500